### ISSUE TITLE
https-portal example, does it work?

### ISSUE THREAD

**Issue by Falieson** [verdaccio/docker-examples#15]
When I go to foobar:4873 this is the verdaccio web client - but not https. When I go to https://foobar:4871 I do get warned of a self-signed ssl, but then I get an nginx bad gateway error. http://foobar:4870 doens't work.

After updating my .npmrc
```
registry=https://foobar:4871/
strict-ssl=false
```

I tried doing an `npm i -S @scope/example` (the package that comes w/ the example), still no success.

Thanks for anyone's direction with this, I haven't used https-portal before. 

**docker-compose.yml**
```
version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio-https
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"

  https-portal:
    image: steveltn/https-portal:1
    container_name: verdaccio-portal
    ports:
      - '4870:80'
      - '4871:443'
    links:
      - verdaccio:verdaccio
    environment:
      DOMAINS: 'foobar -> http://foobar:4873'
      STAGE: local
```
