### ISSUE TITLE
Kubernetes example

### ISSUE THREAD

**Issue by TrejGun** [verdaccio/docker-examples#21]
kubernetes example says

```
➜  ~ kubectl logs verdaccio-deployment-64d64f5d95-z4nft -p
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- invalid address - http://0.0.0.0:tcp://10.111.233.6:4873, we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```

**Comment by TrejGun** [comment]
Hi @juanpicado 
what kind of info do you need?
I'm running macOS 10.14.5

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
➜  ~ minikube version
minikube version: v1.0.0
```

**Comment by juanpicado** [comment]
The reason for opening this issue, it is not clear. What's the issue? etc etc ...all I need to know to help you.

**Comment by TrejGun** [comment]
I'm trying  to run code from `kubernetes-example` folder but pod stucks in CrashLoopBackOff
i'm total noob in kebernetes but it looks like a missconfiguration in this part
```
http://0.0.0.0:tcp://10.111.233.6:4873
```
I have also tried to run doker version and it works, so this is definetely missconfiguration of kubernetes
Can you please take a look?

**Comment by DanielRuf** [comment]
Probably some wrong value in the config file. Can you share the relevant part with us?

**Comment by TrejGun** [comment]
i did not changhe any values just run code from `kubernetes-example`

**Comment by DanielRuf** [comment]
Ah ok, thanks for the info.

**Comment by TrejGun** [comment]
this works

deployment.yaml
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: verdaccio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
      - name: verdaccio
        image: verdaccio/verdaccio
        imagePullPolicy: Always
        ports:
          - containerPort: 4873
```

service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
spec:
  type: NodePort
  selector:
    app: verdaccio
  ports:
  - port: 4873
    targetPort: 4873
    nodePort: 30061
    protocol: TCP
```

ingfress.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: verdaccio-ingress
spec:
  backend:
    serviceName: verdaccio-service
    servicePort: 4873
```

```bash 
➜  kubernetes-example git:(master) ✗ minikube service verdaccio-service --url
http://192.168.99.101:30061
```

Can make PR if you are interested
